### ISSUE TITLE
Provide convenience methods to check rights over a collection of Identities (Principal)

### ISSUE THREAD

**Issue by sandorfr** [geeklearningio/gl-dotnet-authorizations#10]
That will enable easy implementation of scenario like groups or impersonation.

**Comment by sandorfr** [comment]
@arnaudauroux  I think you are doing work around group which might be related or deprecate this.

**Comment by arnaudauroux** [comment]
@sandorfr Exactly, the implementation is in progress. A group will act as a principal and will provide a group hierarchy mecanism. Moreover, it is a best practice to assign a role to group and never directly to an user even it means to have a one user group.

**Comment by sandorfr** [comment]
I think the new Hierarchical groups covers most scenarios I had in mind, If someone need this it's pretty easy to implement.
