### ISSUE TITLE
Rename Role to RightSet or PermissionSet

### ISSUE THREAD

**Issue by sandorfr** [geeklearningio/gl-dotnet-authorizations#13]
Role in the library refers to a `set of rights`. An actual Functional Role implementation will in many cases require various right sets on different scopes.

**Comment by arnaudauroux** [comment]
Indeed an ACL role is a technical data which is part of the authorization triangle (Authorization = Role on a Scope for a Security Identity). So the role is limited by the scope and has not the same meaning than a functional role which is represented, as you said, by several data association. So the Role, within an ACL context, has a very limited meaning.  It could be for instance Reader (with rights: Read), Writer (with rights: Read + Write), Admin (with rights: Read + Write + Delete) etc. But it is a totally different purpose that a functional role like Business Unit Manager which has a role Admin on the scope of a business unit and a role Reader on a higher structure level for example.
On the whole, RightSet or PermissionSet could be a valid name but it does not sound like an ACL standard, does it ?
