### ISSUE TITLE
SQL Scripts are Out of date

### ISSUE THREAD

**Issue by sandorfr** [geeklearningio/gl-dotnet-authorizations#34]

**Comment by sandorfr** [comment]
They are now missing ;)

**Comment by arnaudauroux** [comment]
Yes I would like to be MS SQL Server independent so i try to figure out a solution to use the EF Core migration mechanism to do the same thing ;)

**Comment by sandorfr** [comment]
Sounds like a stretch goal to me. I like being able to manage this as part of the dacpac.

**Comment by arnaudauroux** [comment]
Yes but this creates a strong dependency whereas the others parts are data technologies agnostic. I don't see any reason to be SQL Server focus except if we cannot found any elegant solution to do so.

**Comment by arnaudauroux** [comment]
For the time being, let's split the difference ;) I intend to re-add the SQL Server scripts as part of the solution without link them to any project. It will be effective in the next alpha.
