### ISSUE TITLE
A call of `AddPrincipalToGroupAsync` doesn't cancel a previous call of `RemovePrincipalFromGroupAsync`

### ISSUE THREAD

**Issue by asiffermann** [geeklearningio/gl-dotnet-authorizations#54]
We should bring idempotency to the groups' APIs [like it is done in the scopes' APIs](https://github.com/geeklearningio/gl-dotnet-authorizations/blob/develop/src/GeekLearning.Authorizations.EntityFrameworkCore/AuthorizationsManager.cs#L554).

**Comment by arnaudauroux** [comment]
Fixed in release 0.1.0-alpha220
